server {

    # Nginx слушает 80 порт внутри контейнера
    listen 80;

    # Домен/хост
    server_name localhost;

    # Корневая папка проекта
    # Laravel должен смотреть именно в /public
    root /var/www/html/public;

    # Какие файлы считать стартовыми
    index index.php index.html;

    # Обработка обычных HTTP-запросов
    location / {

        # Сначала пытаемся найти:
        # 1. файл
        # 2. папку
        # Если не найдено —
        # отправляем запрос в Laravel router через index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Обработка PHP-файлов
    location ~ \.php$ {

        # Отправляем PHP-запросы в контейнер php
        # php — имя сервиса из docker-compose.yml
        # 9000 — порт PHP-FPM
        fastcgi_pass php:9000;

        # Главный PHP-файл
        fastcgi_index index.php;

        # Полный путь до PHP-файла
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;

        # Подключаем стандартные FastCGI параметры
        include fastcgi_params;
    }

    # Запрет доступа к скрытым файлам
    # Например .env
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
